# Generated by Django 4.2.3 on 2023-07-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='works/'),
        ),
    ]
