# Generated by Django 4.2.3 on 2023-07-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_work_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='buy_now_url',
        ),
    ]
