# Generated by Django 4.2.3 on 2023-07-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_work_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
    ]
